### ISSUE TITLE
Segmentation Support

### ISSUE THREAD

**Issue by amitbcp** [Heonjin/IIC-custom#1]
I was trying to experiment with IIC, and was looking for a more new build with Python3 & pytorch >=1.0
I cam across the repository. Thanks for open sourcing it.
Could you please help me to understand , does the implementation support segmentation and pytorch>1.0 ?

**Comment by Heonjin** [comment]
> I was trying to experiment with IIC, and was looking for a more new build with Python3 & pytorch >=1.0
> I cam across the repository. Thanks for open sourcing it.
> Could you please help me to understand , does the implementation support segmentation and pytorch>1.0 ?

Hi. Glad this repo. helps somebody. Yes, of course. This code supports the semantic image segmentation. If you are looking for the additional version requirements, then see this

**Comment by amitbcp** [comment]
Thanks @Heonjin !
